Feat/login-page
jmporchet/bravakin-client pull request #4
Opened 2017-08-14 18:19 UTC by alexsicart

2017-08-14 18:20 UTC, jmporchet requested changes
not ready for merge, lacks CSS styling and redirection

2017-08-15 15:47 UTC, alexsicart reviewed
Ready for merge, but lacks of css in the sign up part, needs @arol reviews.

2017-08-15 15:51 UTC, arol submitted a review, later dismissed

2017-08-15 15:51 UTC, arol commented on src/components/Homepage.js
> +      return <Redirect to="/preferences" />
Keep in mind that this only occurs the first time. I would redirect to `/` and then there (`Authenticated` component), if the user miss some config, you always kick it back to `/preferences`

2017-08-15 15:51 UTC, arol commented
One does not simply get a conflict on the `package-log.json` file

2017-08-15 18:04 UTC, jmporchet approved these changes

2017-08-15 18:04 UTC, merged